[package]
name = "astridyz/amiya"
description = "Modern components for Fusion"
license = "MIT"
authors = ["Astrid"]
version = "0.1.0"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Fusion = "elttob/fusion@0.3.0"